---
# handlers file for rhel7-role-stig-rhel7-disa
- name: firewalld reload
  command: firewall-cmd --reload

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted
  listen: "restart firewalld"
